[project]
authors = ["Mohammad"]
entry = "main.sw"
license = "Apache-2.0"
name = "incrementor_test"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "master" }
incrementor_abi = { path = "../incrementor_abi" }
