[project]
authors = ["Mohammad"]
entry = "main.sw"
license = "Apache-2.0"
name = "incrementor_contract"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway-lib-std" }
incrementor_abi = { path = "../incrementor_abi" }
