[project]
authors = ["Mohammad"]
entry = "main.sw"
license = "Apache-2.0"
name = "ex1"

[dependencies]
core = { path = "../../../sway-lib-core" }
std = { git = "https://github.com/FuelLabs/sway-lib-std" }
